#### conda create --name tf tensorflow-gpu

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
conda list

# packages in environment at /home/pirl/anaconda3/envs/tf:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.0                    py36_0  
astor                     0.7.1                    py36_0  
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    pypi_0    pypi
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
cudatoolkit               9.2                           0  
cudnn                     7.3.1                 cuda9.2_0  
cupti                     9.2.148                       0  
dbus                      1.13.6               h746ee38_0  
decorator                 4.3.2                    py36_0  
entrypoints               

### numpy array

In [3]:
a = np.array([
    [2.1,3.1,3.9],
    [3.2,4.5,3.1]
])

In [4]:
print(a)
print(a.shape)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]
(2, 3)


In [6]:
np.mean(a, axis = 0)

array([2.65, 3.8 , 3.5 ])

In [7]:
a+3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

### tensorflow

Data : 2차원 평면에 존재하는 점들  
Feature : 가지고 있는 데이터를 '어떻게 표현하면 좋을까'를 나타내는 표현  
Hidden layer : iteration이 돌수록 weight가 줄어듬  
loss : training loss => 트레이닝셋으로부터 나온 loss, test loss => 테스트셋으로부터 나온 loss cf)둘이 비슷하면 좋다 (train loss < test loss)  
epoch : 전체 트레이닝셋을 한 번 봤을 때 1 epoch cf)batch size는 보통 2진수로 둔다